---
kind: pipeline
name: react-ci-cd

steps:
  - name: deps
    image: node:alpine
    commands:
      - npm install
  - name: build
    image: node:alpine
    commands:
      - npm run build
  - name: test
    image: node:alpine
    commands:
      -  npm test
  - name: prerelease
    image: alpine
    commands:
      - tar -zcvf build.tar.gz build/
    when:
      event: tag
  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - build.tar.gz
    when:
      event: tag
  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
    channel: test-ci-victor
    username: drone
