---
kind: pipeline
name: react-ci-cd

steps:
  - name: echo
    image: node:alpine
    commands:
      - echo 'Run CI / CD Pipeline on Drone'
  - name: deps
    image: node:alpine
    commands:
      - npm install
  - name: build
    image: node:alpine
    commands:
      - npm run build
  - name: test
    image: node:alpine
    commands:
      -  npm test
  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
    channel: test-ci-victor
    username: drone
